root: true

parserOptions:
  sourceType: script

plugins:
  - node
  - unicorn

env:
  node: true

extends:
  - eslint:recommended
  - xo/esnext
  - plugin:unicorn/recommended
  - plugin:node/recommended
  - plugin:prettier/recommended

rules:
  strict: 2
  capitalized-comments: 0
  # unicorn https://github.com/sindresorhus/eslint-plugin-unicorn
  unicorn/filename-case: 0
  # node https://github.com/mysticatea/eslint-plugin-node
  node/no-unsupported-features: ["error", {
    "version": 7.6.0,
    "ignores": []
  }]
  node/no-unpublished-require: 0
